sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: ddw99402
  alioss:
    access-key-id: LTAI5tC4q5YPNNhAd4dxi5r8
    access-key-secret: zRmUji857J7xpfbygIN72a5IXoZakJ
    bucket-name: sky-ddv
    endpoint: oss-cn-beijing.aliyuncs.com
  redis:
    host: localhost
    port: 6379
    database: 1